aullman/opentok-meet

public/css/main.css, public/css/subscriber-stats.css, public/js/subscriber-stats.js, tests/e2e/scenarios.js, tests/protractor.conf.js, tests/unit/subscriberStatsSpec.js, views/room.ejs
Now when you mouse over the Subscriber there is a little stats icon in the top left corner. If you mouse over it you get some stats about the subscriber. Namely:
Resolution
Audio Packet Loss
Audio Bitrate
Video Packet Loss
Video Bitrate
=> Adding a subscriber stats button

.gitignore, .travis.yml, app.js, package.json, server/routes.js, tests/e2e/scenarios.js, tests/protractor-browserstack.conf.js
Running protractor tests on browser stack now from Travis.
=> Browserstack

.gitignore, .tern-project, .travis.yml, package.json, tests/e2e/scenarios.js, tests/firefox-helper.js, tests/protractor.conf.js
Also testing Firefox Beta and Chrome Beta is no longer allowed to fail.
=> Don't use Browserstack for Firefox testing

bower.json, public/css/main.css, views/room.ejs, views/whiteboard.ejs
=> Updating the whiteboard to use the new version with smoothing

public/css/main.css, src/js/controllers.js, src/js/directives.js, tests/unit/controllersSpec.js, tests/unit/directivesSpec.js, views/room.ejs
Displays a 'Reconnecting...' message once the `sessionReconnecting` event arrives until a `sessionReconnected`, `sessionConnected` or `sessionDisconnected` event arrives.
=> OPENTOK-29082 - Add some UI to meet when you're reconnecting

tests/e2e/scenarios.js
Fixing tests to not assume a fixed resolution.
=> Simulcast messes with the dimensions

package.json
This should use the newer chromedriver which works with Chrome 54.
=> #142 Update to a newer protractor

CONTRIBUTING.md, app.js, package.json, plugins/archiving/index.js, plugins/screen/index.js, plugins/whiteboard/index.js, server/routes.js
Adding @ggarber's plugin architecture and migrating archiving, whiteboard and screen to use it. Also adding contributing guidelines which indicate that you should use the plugin architecture.
=> Plugin architecture

public/css/index.css, src/js/login/controller.js, tests/e2e/loginScenarios.js, tests/unit/login/controllerSpec.js, views/index.ejs
Fixes #69 - add advanced features
=> Feature room types

package.json, src/js/notifications.js, tests/unit/notificationsSpec.js
* Using push.js to trigger notifications which means that the notifications should work on mobile
* Notifications timeout after 5 seconds
* Notifications replace eachother instead of building up
* Clicking on a notification focuses the window and closes the notification
* A notification does not fire for your own connectionCreated event
=> fixes #150 - mobile notifications with push.js

package.json, src/js/controllers.js, src/js/services.js
Submitting https://github.com/aullman/opentok-meet/pull/159 from the same repo so that the tests run.
=> Aiham fix/update angular version

public/css/main.css, src/js/directives.js, tests/e2e/roomScenarios.js, tests/unit/directivesSpec.js, views/room.ejs
Added a mute video and mute audio buttons to the bottom. Also added a label to the buttons and made the buttons move to the left hand side if the window is too narrow.
=> Issue 76 - Adding mute audio and mute video buttons that work on Android devices

package.json, public/css/main.css, src/js/app.js, src/js/controllers.js, tests/e2e/textchatScenarios.js, tests/karma.conf.js, views/room.ejs, webpack.config.js
This fixes #61 
Adding https://github.com/aullman/opentok-textchat
=> Adding Textchat

.travis.yml, package.json
In the hopes that this will make npm install quicker
=> Update node and npm versions

package.json, public/css/main.css, src/js/controllers.js, src/js/directives.js, tests/e2e/2browserScenarios.js, tests/protractor.conf.js, tests/unit/controllersSpec.js, views/room.ejs, yarn.lock
Now we maintain aspect ratio by default unless you click the zoom button then it will zoom in
=> Adding a zoom button

package-lock.json, package.json, plugins/archiving/index.js, yarn.lock
Resubmitting PR from the same repo so that the Travis tests can run. See https://github.com/aullman/opentok-meet/pull/202 for details
=> Jpujol feature/hd archiving

.travis.yml, package.json, src/css/cycle-camera.css, src/js/directives.js, tests/unit/directivesSpec.js, views/room.ejs, yarn.lock
Adding a cycleCamera button to switch between front and rear cameras
=> Cycle camera

src/js/directives.js
Dispatch otLayout asynchronously so there is enough time for the view to update
=> Fix wonky expand bug

package.json, yarn.lock
This has a fix for the capture functionality.
=> Upgrade to newer opentok-whiteboard

package.json, src/css/microphone-picker.css, src/js/app.js, src/js/microphone-picker.js, src/templates/microphone-picker.html, tests/unit/index.js, tests/unit/microphonePickerSpec.js, views/room.ejs, yarn.lock
now that 2.15 is in production and `publisher.setAudioSource()` is available we can add the microphone picker here.
See https://github.com/opentok/opentok-meet/pull/67 for the original PR.
=> OPENTOK-37632 - cherry-picking microphone picker over

.eslintrc.js, .travis.yml, package.json, server/roomstore.js, src/css/cycle-camera.css, src/css/filter-picker.css, src/js/app.js, src/js/controllers.js, src/js/filter-picker.js, src/js/filtered-publisher.js, src/templates/filter-picker.html, tests/e2e/roomScenarios.js, tests/e2e/screenScenarios.js, tests/firefox-helper.js, tests/karma.conf.js, tests/unit/controllersSpec.js, tests/unit/notificationsSpec.js, tests/unit/screen/controllerSpec.js, views/room.ejs, webpack.config.js, yarn.lock
=> Adding a filter picker using opentok-camera-filters
